jwt:
    signerKey: "wVKQCLiM3nXVQWu1FE+V46tWjCrRJh7AyEUKB1YStWnJu84fhm6AgFZ2vklKk+8u"
    valid-duration: 10 # seconds
    refreshable-duration: 120 # seconds
server:
    port: 8080
    servlet:
        context-path: /identity
spring:
    application:
        name: identity-service
    datasource:
        password: root
        url: jdbc:mysql://localhost:3307/identity_service
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
